### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by bregman-arie** [Mariii123/sidescroller#1]
I'm unable to start the game. I get the following error:

Traceback (most recent call last):
  File "sidescroller.py", line 24, in <module>
    spimg=[pygame.image.load("s"+str(i)+'.png').convert_alpha() for i in range(1,6)]
pygame.error: Couldn't open s1.png

**Comment by Marishwaran99** [comment]
spimg=[pygame.image.load("S"+str(i)+'.png').convert_alpha() for i in range(1,6)]

just replace small s by capital S

**Comment by Marishwaran99** [comment]
you does not require that line because i had not used that but i am sure that i will be using in further
so right now you does not require that
i have updated the code

**Comment by bregman-arie** [comment]
Thanks but it's still not working:

Traceback (most recent call last):
  File "sidescroller.py", line 25, in <module>
    sawimg=[pygame.image.load("saw"+str(i)+'.png').convert_alpha() for i in range(4)]
pygame.error: Couldn't open saw0.png

**Comment by Marishwaran99** [comment]
replace saw to SAW

**Comment by Marishwaran99** [comment]
just put appropriate name of image which you stored

**Comment by bregman-arie** [comment]
Yes, I know how to workaround it manually but I opened the issue so we can have a proper fix in the code.

**Comment by Sandeep-Ghimire** [comment]
Clearly the code is not using the absolute directory.How about changing the current directory

**Comment by Marishwaran99** [comment]
I am not able to get you

**Comment by bregman-arie** [comment]
Looks like it's impossible to communicate the issue. I'm closing it now.
